name: FroobMechs
main: com.froobworld.froobmechs.FroobMechs
author: froobynooby
version: 3.4.0
api-version: 1.13
description: >
             Server utilities.
commands:
   orestats:
    description: Get stats on a player's mining activities.
    aliases: [os]
   pvp:
    description: Toggle PvP.
   mess:
    description: Report a messy area at your location.
   listmesses:
    description: Get a list of reported messy areas.
   tpmess:
    description: Teleport to a reported messy area.
   closemess:
    description: Mark a reported messy area as cleaned.










